@API=http://localhost:3000/api

### games
GET {{API}}/games

### create
POST {{API}}/games
Content-Type: application/json

{
    "player": "maé"
}

### game
GET {{API}}/games/game1

### join
PUT {{API}}/games/game1/join
Content-Type: application/json

{
    "player": "ju"
}

### hit
PUT {{API}}/games/game1/hit
Content-Type: application/json

{
    "target": "player1",
    "coords": {
        "x": 3,
        "y": 1
    }
}

### bus
curl -N http://localhost:3000/api/games/game1/players/player1/events
